spring.datasource.url=${TEST_DB_URL}
spring.datasource.username=${TEST_DB_USERNAME}
spring.datasource.password=${TEST_DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect