spring.datasource.url=${Test_DB_URL}
spring.datasource.username=${Test_DB_USERNAME}
spring.datasource.password=${Test_DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Optional but recommended
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


server.port=8088